Repository young-seung/msa-example, pull requests merged in 2020-05, with the labels that each got.

#8 File service
  file/.aws/buckets.sh
  file/.env
  file/docker-compose.dev.yml
  file/src/main/resources/application.properties
Labels: bug, help wanted

#9 Add POST /profiles
  profile/package-lock.json
  profile/package.json
  profile/src/account/application/command/handlers/account.handler.command.create.ts
  profile/src/account/application/command/handlers/account.handler.command.delete.ts
  profile/src/account/application/event/handlers/account.handler.event.compare-password.ts
  profile/src/account/application/query/handlers/account.handler.query.list.ts
  profile/src/account/application/query/handlers/account.handler.query.ts
  profile/src/account/domain/model/account.model.ts
  profile/src/account/infrastructure/redis/account.redis.ts
  profile/src/app.module.ts
  profile/src/profile/application/command/handler/profile.handler.command.create.ts
  profile/src/profile/application/command/implements/profile.command.create.ts
  profile/src/profile/domain/model/profile.model.ts
  profile/src/profile/dto/profile.dto.create.ts
  profile/src/profile/infrastructure/entity/profile.entity.ts
  profile/src/profile/infrastructure/mapper/profile.mapper.create.ts
  profile/src/profile/infrastructure/repository/profile.repository.ts
  profile/src/profile/profile.controller.spec.ts
  profile/src/profile/profile.controller.ts
  profile/src/profile/profile.module.ts
Labels: enhancement

#10 Account service
  account/account/command/create.handler.go
  account/account/repository/main.go
  account/docs/docs.go
Labels: enhancement

#11 Add file example code with jpa mysql setting
  file/src/main/kotlin/com/example/file/controller/FileController.kt
  file/src/main/kotlin/com/example/file/model/File.kt
  file/src/main/kotlin/com/example/file/repository/FileRepository.kt
  file/src/main/resources/application.properties
  file/src/test/kotlin/com/example/file/DemoApplicationTests.kt
Labels: enhancement

#14 Add GET /files?account_id=&usage= for get file list
  file/commandbus/create.go
  file/controller/create.go
  file/controller/main.go
  file/controller/read.go
  file/docs/docs.go
  file/docs/swagger.json
  file/docs/swagger.yaml
  file/model/main.go
  file/querybus/main.go
  file/querybus/read.go
  file/repository/main.go
Labels: bug, enhancement

#16 Modify directory tree
  account/account/main.go
  account/body/main.go
  account/command/create.go
  account/command/create.handler.go
  account/command/delete.go
  account/command/delete.handler.go
  account/command/main.go
  account/command/update.go
  account/command/update.hendler.go
  account/controller/create.go
  account/controller/delete.go
  account/controller/main.go
  account/controller/main_test.go
  account/controller/read.go
  account/controller/update.go
  account/docs/docs.go
  account/dto/main.go
  account/entity/account.go
  account/go.mod
  account/go.sum
  account/main.go
  account/model/account.go
  account/query/main.go
  account/query/read.go
  account/query/read.handler.go
  account/repository/main.go
Labels: enhancement

#22 Add user service
  user/.dockerignore
  user/.env
  user/.eslintignore
  user/.eslintrc
  user/.gitignore
  user/.prettierrc
  user/Dockerfile
  user/README.md
  user/docker-compose.development.yml
  user/docker-compose.yml
  user/nginx.conf
  user/nodemon.json
  user/package-lock.json
  user/package.json
  user/src/app.config.ts
  user/src/app.controller.ts
  user/src/app.module.ts
  user/src/main.ts
  user/src/users/command/create.handler.ts
  user/src/users/command/create.result.ts
  user/src/users/command/create.ts
  user/src/users/command/delete.handler.ts
  user/src/users/command/delete.result.ts
  user/src/users/command/delete.ts
  user/src/users/command/update.handler.ts
  user/src/users/command/update.result.ts
  user/src/users/command/update.ts
  user/src/users/dto/create.response.ts
  user/src/users/dto/create.ts
  user/src/users/dto/delete.response.ts
  user/src/users/dto/find.response.ts
  user/src/users/dto/find.ts
  user/src/users/dto/findById.response.ts
  user/src/users/dto/update.response.ts
  user/src/users/dto/update.ts
  user/src/users/entity/event.ts
  user/src/users/entity/user.ts
  user/src/users/event/created.ts
  user/src/users/event/deleted.ts
  user/src/users/event/updated.handler.ts
  user/src/users/event/updated.ts
  user/src/users/model/user.model.ts
  user/src/users/query/find.handler.ts
  user/src/users/query/find.result.ts
  user/src/users/query/find.ts
  user/src/users/query/findById.handle.ts
  user/src/users/query/findById.result.ts
  user/src/users/query/findById.ts
  user/src/users/users.controller.spec.ts
  user/src/users/users.controller.ts
  user/tsconfig.build.json
  user/tsconfig.json
Labels: enhancement
